// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Artifact = {
  created_at: ISODateString
  created_by: UUID<"profiles"> | null
  id: UUID<"artifacts">
  kind: "pdf" | "image" | "note" | "output"
  page_count: number | null
  session_id: UUID<"sessions">
  slot: "main" | "note" | null
  storage_path: string | null
  title: string | null
}
