// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Board = {
  created_at: ISODateString
  id: UUID<"boards">
  name: string
  team_id: UUID<"teams">
}
