// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { UUID } from "./common"

export type BoardColumn = {
  board_id: UUID<"boards">
  id: UUID<"board_columns">
  name: string
  position: number
}
