// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type HighlightNote = {
  content: string
  created_at: ISODateString
  highlight_id: UUID<"highlights">
  id: UUID<"highlight_notes">
  ink: Json | null
  input_mode: "keyboard" | "ink" | "stylus_os"
  profile_id: UUID<"profiles">
  transcribed_at: ISODateString | null
  transcribed_by: string | null
  updated_at: ISODateString
  version: number
  visibility: "individual" | "group"
}
