// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type Highlight = {
  artifact_id: UUID<"artifacts">
  bbox: Json | null
  confidence: number | null
  created_at: ISODateString
  extraction: "text_layer" | "ocr"
  id: UUID<"highlights">
  layer: "individual" | "group"
  page: number | null
  profile_id: UUID<"profiles">
  shared_at: ISODateString | null
  slug: string | null
  text: string
  updated_at: ISODateString
  weight: number
}
