// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type HighlightTermWeight = {
  hit_count: number
  profile_id: UUID<"profiles">
  term: string
  updated_at: ISODateString
  weight: number
}
