// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { UUID } from "./common"

export type LlmProvider = {
  base_url: string
  id: UUID<"llm_providers">
  is_active: boolean
  key: string
  label: string
}
