// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type LlmRequest = {
  completion_tokens: number
  cost: number
  created_at: ISODateString
  error: string | null
  id: UUID<"llm_requests">
  key_source: "user" | "shared"
  latency_ms: number | null
  model_id: UUID<"llm_models"> | null
  profile_id: UUID<"profiles"> | null
  prompt_tokens: number
  session_id: UUID<"sessions"> | null
  stage_id: UUID<"pipeline_stages"> | null
  status: "pending" | "running" | "done" | "failed" | "cancelled"
}
