// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { UUID } from "./common"

export type LlmModel = {
  context_window: number | null
  id: UUID<"llm_models">
  input_cost: number
  is_active: boolean
  is_free_tier: boolean
  label: string | null
  model_key: string
  output_cost: number
  provider_id: UUID<"llm_providers">
}
