// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type MemoryEntry = {
  content: string
  created_at: ISODateString
  created_by: UUID<"profiles"> | null
  embedding: string | null
  id: UUID<"memory_entries">
  kind: "idea" | "limitation"
  persona_id: UUID<"user_personas"> | null
  scope: "persona" | "group" | "conversation" | "initial"
  session_id: UUID<"sessions"> | null
  team_id: UUID<"teams"> | null
}
