// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type MiniConclusion = {
  content: string
  created_at: ISODateString
  highlight_id: UUID<"highlights">
  id: UUID<"mini_conclusions">
}
