// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type PersonaDiscipline = {
  created_at: ISODateString
  description: string | null
  id: UUID<"persona_disciplines">
  is_active: boolean
  key: string
  label: string
  schema: Json
}
