// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type PipelineRun = {
  created_at: ISODateString
  finished_at: ISODateString | null
  id: UUID<"pipeline_runs">
  mode: "planning" | "descriptive" | "visualize"
  owner_profile_id: UUID<"profiles"> | null
  session_id: UUID<"sessions">
  started_at: ISODateString | null
  status: "pending" | "running" | "done" | "failed" | "cancelled"
}
