// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type PipelineStage = {
  error: string | null
  finished_at: ISODateString | null
  id: UUID<"pipeline_stages">
  input: Json | null
  output: Json | null
  run_id: UUID<"pipeline_runs">
  stage: "scope_anchor" | "analytic" | "research" | "validation" | "questioning" | "research_scoped" | "result"
  started_at: ISODateString | null
  status: "pending" | "running" | "done" | "failed" | "cancelled"
}
