// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Point = {
  content: string
  created_at: ISODateString
  highlight_id: UUID<"highlights"> | null
  id: UUID<"points">
  parent_point_id: UUID<"points"> | null
  position: number
  run_id: UUID<"pipeline_runs">
}
