// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type PointConclusion = {
  conclusion: string
  confidence_label: string | null
  created_at: ISODateString
  id: UUID<"point_conclusions">
  open_question: string | null
  point_id: UUID<"points">
  temperature: number
}
