// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type ProfileIdentity = {
  auth_user_id: UUID
  email: string
  id: UUID<"profile_identities">
  is_primary: boolean
  kind: "internal" | "individual"
  linked_at: ISODateString
  profile_id: UUID<"profiles">
}
