// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Profile = {
  avatar_url: string | null
  created_at: ISODateString
  email: string
  full_name: string | null
  id: UUID<"profiles">
  locale: string
  secondary_email: string | null
  secondary_email_verified_at: ISODateString | null
  updated_at: ISODateString
}
