// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type RunRendering = {
  content_md: string | null
  created_at: ISODateString
  diagram_kind: "mermaid" | "flow" | null
  diagram_spec: Json | null
  edited_by: UUID<"profiles"> | null
  id: UUID<"run_renderings">
  is_user_edited: boolean
  mode: "planning" | "descriptive" | "visualize"
  run_id: UUID<"pipeline_runs">
  updated_at: ISODateString
}
