// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Session = {
  column_id: UUID<"board_columns">
  created_at: ISODateString
  created_by: UUID<"profiles"> | null
  default_mode: "planning" | "descriptive" | "visualize"
  id: UUID<"sessions">
  initial_question: string
  internet_ratio: number
  message_cap: number
  position: number
  scope_embedding: string | null
  status: "draft" | "running" | "done" | "archived"
  team_persona_id: UUID<"team_personas"> | null
  title: string
  updated_at: ISODateString
  user_persona_id: UUID<"user_personas"> | null
}
