// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type TeamMember = {
  joined_at: ISODateString
  profile_id: UUID<"profiles">
  role: "leader" | "admin" | "member" | "viewer"
  team_id: UUID<"teams">
}
