// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type Team = {
  created_at: ISODateString
  created_by: UUID<"profiles"> | null
  id: UUID<"teams">
  name: string
  slug: string
}
