// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type TeamPersona = {
  applies_to_stages: "scope_anchor" | "analytic" | "research" | "validation" | "questioning" | "research_scoped" | "result"[]
  created_at: ISODateString
  decided_by: UUID<"profiles"> | null
  guard_prompt: string
  id: UUID<"team_personas">
  is_active: boolean
  name: string
  team_id: UUID<"teams">
  updated_at: ISODateString
  validation_criteria: Json
}
