// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, Json, UUID } from "./common"

export type UserPersona = {
  attributes: Json
  created_at: ISODateString
  discipline_id: UUID<"persona_disciplines"> | null
  id: UUID<"user_personas">
  is_active: boolean
  name: string
  owner_profile_id: UUID<"profiles"> | null
  system_prompt: string
  updated_at: ISODateString
}
