// GENERATED by scripts/gen-domain-types.mjs from `supabase gen types typescript`. Do not edit: run `npm run gen:types`.
import type { ISODateString, UUID } from "./common"

export type UserLlmKey = {
  created_at: ISODateString
  id: UUID<"user_llm_keys">
  label: string | null
  last_validated_at: ISODateString | null
  profile_id: UUID<"profiles">
  provider_id: UUID<"llm_providers">
  status: "active" | "invalid" | "revoked"
  vault_secret_id: UUID
}
