import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import architecture from "./eslint.architecture.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // One rule per architecture invariant (task 000, package E); this file owns none of them.
  ...architecture,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Serwist at build time (git-ignored too):
    "public/sw.js",
    "public/swe-worker-*.js",
  ]),
]);

export default eslintConfig;
